spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/taoyupu/config-repo
          username: 15756270374@163.com
          password: yuanyuan.1314520
          default-label: master
          search-paths: /**
#          basedir: D:/test
      discovery:
              # 指定Config Server在服务发现中的service Id ,默认为configserver
              service-id: ARTISAN-CONFIG
              # 表示使用服务发现组件中的Config Server,而不自己指定Config Server的uri,默认为false
              enabled: true
#  rabbitmq:					#本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
# 以下配置适用于前期调试配置刷新功能，如果配置了自动刷新则不需要该配置
# 手动刷新接口地址 http://localhost:9090/actuator/bus-refresh
# 官方文档地址 https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#_bus_refresh_endpoint
management:
  endpoints:  # 暴露bus 接口 ，否则 更新 refresh 没用的
    web:
      exposure:    # expose: "*" 已过期
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true